In [2]:
# Numpy is a linear algebra library
# Numerical python
# Advantages - It takes less memory and time execution is very fast , Easier to use
# NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
# It performs operations in chunks instead of element by element


In [3]:
import numpy as np
a=[1,2,3]
b=np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
a=[1,2,3,'a','d',4.5]
b=np.array(a)
print(b) # Numpy can only contain elements of homogeneous type


['1' '2' '3' 'a' 'd' '4.5']


In [9]:
a=[1,2,3,4.5,'6']
b=np.array(a,dtype=float)
print(b)

[1.  2.  3.  4.5 6. ]


In [11]:
b=np.ones(3,dtype=int)
print(b)

[1 1 1]


In [13]:
b=np.zeros(3,dtype=int)
print(b)

[0 0 0]


In [15]:
# 2d array
b=np.ones((3,3,),dtype=int)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
b=np.full(3,5)
print(b)

[5 5 5]


In [19]:
b=np.full((3,3),10)
print(b)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [23]:
# empty function returns random values in array
b=np.empty((3,3))
print(b)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 8.30030285e-321]
 [1.05699242e-307 3.11523242e-307 5.68175493e-322]]


In [28]:
# 2d array using .array function
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
b=np.zeros(9,dtype=int)
b[4]=1
print(b)

[0 0 0 0 1 0 0 0 0]


In [34]:
# .arrange control over step value
b=np.arange(10) # start is 0, stop is 10,step is 1
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
b=np.arange(1,11,2)
b

array([1, 3, 5, 7, 9])

In [61]:
# linspace control over no of values
b=np.linspace(2,10,10)
b

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [44]:
b=np.linspace(2,10,5,dtype=int)
b

array([ 2,  4,  6,  8, 10])

In [46]:
b=np.linspace(2,10,5,dtype=int,endpoint=False)
b

array([2, 3, 5, 6, 8])

In [48]:
# identity matrix
b=np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
b=np.eye(3,4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [6]:
b=np.random.rand(10)*10
b

array([8.23883006, 9.14350135, 9.18902148, 4.16588243, 5.34491871,
       9.70594955, 2.21376248, 1.71044512, 5.91883559, 7.54206247])

In [5]:
# for rounding off the value 
b=np.random.rand()
b
np.around(b,2)

0.05

### Slicing and Indexing

In [7]:
arr=np.array([1,2,3,4,5])
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [11]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1:3])
print(arr[1][2])
print(arr[1,2])

[[4 5 6]
 [7 8 9]]
6
6


In [21]:
# slicing
print(arr[0:3][2]) # in this case first 0:3 occurs then 2 occurs
ans=arr[0:3,2]# but in this case it works differently
print(ans)
# Using numpy we can access any part of a 2d matrix but we cannot do so with the help of lists

[7 8 9]
[3 6 9]


# Mathematical Operations

In [31]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
a=a+1
print(a)

[1 2 3 4 5]
[2 3 4 5 6]


In [41]:
b=np.array([1,1,1,1,1])
c=a+b
print(c)

[3 4 5 6 7]


In [54]:
# Functions *,/,**,//,+,-
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())

20
4.0
2
0


In [56]:
print(a)
print(c)
print(a>c)

[2 3 4 5 6]
[3 4 5 6 7]
[False False False False False]


In [57]:
print(a<b)
print(a==b)


[False False False False False]
[False False False False False]


In [60]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [64]:
# for 2d arrays
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[2,3,4],[6,4,2],[1,3,11]])
print(a)
print(a+1)
print(a-1)
print(a*2)
print(a==b)
print(a>b)
print(np.logical_or(a,b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[False False False]
 [False False False]
 [False False False]]
[[False False False]
 [False  True  True]
 [ True  True False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [75]:
# Boolean Indexing
b=np.array([2,11,5,4,33,21,1,4,12])
print(b>10)
bool_arr=b>10
new_arr=b[bool_arr]
print(new_arr)

[False  True False False  True  True False False  True]
[11 33 21 12]


In [76]:
newarr=b[b>10]
print(newarr)

[11 33 21 12]


In [80]:
b[:2]=99
b[b>10]=100
b

array([100, 100,   5,   4, 100, 100,   1,   4, 100])

In [85]:
# To print the indexes of given value
ind=np.where(b==100)
print(ind)

(array([0, 1, 4, 5, 8], dtype=int64),)


In [90]:
# boolean indexing in 2d array
a=np.array([[1,2,3],[3,4,5],[6,7,8]])
bool_arr=a[:,2]!=0
print(bool_arr)
a[bool_arr,2]=99
a

[ True  True  True]


array([[ 1,  2, 99],
       [ 3,  4, 99],
       [ 6,  7, 99]])

## Numpy Broadcasting

In [7]:
 #Broadcasting will tell how numpy will treat operations of two arrays of different sizes
# 2 rules - if dim are same or if one of the dim of both the arrays is one


In [8]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(1,3))
print(x)
print(y)

[[5 9 3]
 [7 7 6]
 [7 5 4]]
[[2 3 9]]


In [10]:
z=x-y
print(z)

[[ 3  6 -6]
 [ 5  4 -3]
 [ 5  2 -5]]


In [ ]:
# more operations np.transpose()
# More Important Operations


# df['CityLocation'].replace('Delhi','New Delhi',inplace = True)


# l=x[i].split(',')
#     for j in range(len(l)):
#         if l[j].strip() in d:
#             d[l[j].strip()]+=1
#         else:
#             d[l[j].strip()]=1
# sort_orders = sorted(d.items(), key=lambda x: x[1], reverse=True)

# def seprateCity(city):
#     return city.split('/')[0].strip()
# df['CityLocation'] = df['CityLocation'].apply(seprateCity)


# def f(string):
#     string = string.replace('.', '')
#     string = string.replace(',', '')
#     return float(string)
# final_df["AmountInUSD"]=final_df["AmountInUSD"].apply(f)

